spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl  
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        generate_statistics: true
        format_sql: true   
    show-sql: true

# Logging
logging:
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
  level:
    root: ERROR
    com.training.mjunction.usersvcs: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    sun.rmi: ERROR
    org.reflections: ERROR
    sun.reflect: ERROR
    org.apache.coyote.http11: ERROR
    org.glassfish.jersey.internal.util: ERROR
    org.apache.tomcat.util.descriptor: ERROR
    org.apache.catalina.core: ERROR
 